services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: eldorg_db
      POSTGRES_USER: eldorg_user
      POSTGRES_PASSWORD: eldorg_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    env_file:
      - .env
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
volumes:
  pgdata:
    driver: local
