spring:
  application:
    name: eldorg
  datasource:
    url: jdbc:postgresql://localhost:5432/eldorg_db
    username: eldorg_user
    password: eldorg_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
